### ISSUE TITLE
How do I use a trained model to generate comparison data?

### ISSUE THREAD

**Issue by SoapJohnMacTavish** [baturaysaglam/DISCOVER#1]
Appreciate your contribution.  I am a beginner in the DRL field, and I noticed that the project only provides training code, so how do I use the trained model? For example, how can I use the code of this project to run diagrams such as 4_reproduced.jpg, 5_reproduced.jpg, and 9_reproduced.jpg? More specifically, how to get the data that leads to these graphs?

**Comment by baturaysaglam** [comment]
I guess that's the wrong repo. please refer to the right one. I'm closing this issue for this
